---
language: node_js
sudo: false
node_js:
  - "stable"
  - "7.1.0"
  - "7.0.0"
  - "6.9.1"
  - "6.5"
  - "6.4"
  - "6.3"
  - "5.12"
  - "4.4"
  - "4.3.2"
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
